version: '3'
services:

  stubrunner:
    image: springcloud/spring-cloud-contract-stub-runner:4.0.4
    environment:
      STUBRUNNER_IDS: ch.keepcalm:kboot-ddd:+:stubs:8081
      STUBRUNNER_STUBS_MODE: REMOTE
      STUBRUNNER_GENERATE_STUBS: TRUE
      STUBRUNNER_REPOSITORY_ROOT: git://https://github.com/marzelwidmer/contracts.git
      LANG: C.UTF-8
    ports:
      - "8081:8081"

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'

