= kboot-ddd with ArchUnit and Onion Architecture

.inMemory version
----
SPRING_PROFILES_ACTIVE=inMemory mvn clean spring-boot:run -pl application-module
----
.Redis version
----
SPRING_PROFILES_ACTIVE=redis mvn clean spring-boot:run -pl application-module
----

* *domain-module*: This module contains your domain models, which are `Partner` and `PartnerName` in this case.

* *application-module*: This module is divided into three main parts:

** *domain*: Contains the `PartnerRepository` interface which defines the operations that can be performed on `Partner`.
** *application*: Contains the application-specific logic, which includes `PartnerController`, `PartnerService`, and `PartnerRepositoryImpl`. The `PartnerRepositoryImpl` is an implementation of the `PartnerRepository` interface.
** *infrastructure*: While it’s currently empty, this is where you’d typically put code that interacts with external systems like databases or web services.
* *etc/rest-client*: Contains an HTTP request file, which is likely used for testing your API endpoints.





```bash
.
└── src
    └── main
        └── kotlin
            └── ch.keepcalm
                └── application (Application layer)
                │   └── partner
                │       └── PartnerService.kt (Service for partner-related operations)
                │
                └── domain (Domain layer)
                │   └── partner
                │       ├── Partner.kt (Domain entity representing a partner)
                │       └── PartnerRepository.kt (Repository interface for partner entities)
                │
                └── infrastructure (Infrastructure layer)
                │   └── partner
                │       └── redis (Redis-specific components)
                │       │   ├── PartnerRedisRepository.kt (Implements the Redis repository for partner data)
                │       │   ├── RedisConfig.kt (Redis configuration)
                │       │
                │       └── mongodb (MongoDB-specific components)
                │       │   ├── PartnerMongoRepository.kt (Implements the MongoDB repository for partner data)
                │       │   ├── MongoConfig.kt (MongoDB configuration)
                │
                └── shared (Shared components used across layers)
                │   └── CommonUtils.kt (Shared utility functions used across the application)
                │
                └── Application.kt (Main application entry point)
                └── WebConfig.kt (Web-related configuration)

```
In this structure:

* *application/partner*: This directory contains the application layer for the "partner" domain.
The PartnerService.kt file likely contains service classes and business logic related to the "partner" domain.

* *domain/partner*: This directory represents the domain layer for the "partner" domain.
The Partner.kt file typically contains the domain model class representing a partner,
and the PartnerRepository.kt file may define the interface for the repository responsible for storing and retrieving partner-related data.

* *infrastructure*:
- The "mongo" folder contains MongoDB-specific components.
- The "redis" folder contains Redis-specific components.
- The "shared" folder can hold shared components like exception classes.






