spring:
  cloud:
    contract:
      verifier:
        enabled: false
  application:
    title: "DDD :: Sample Project :: Onion Architecture"
    name: "kboot-ddd-demo"
  data:
    redis:
      host: localhost
