### Create Partner
POST http://localhost:8080/partners
Content-Type: application/json

{
  "name": "foo"
}

### Get Partner - Add the ID from Create Partner from ServerLog
GET  http://localhost:8080/partners/1d5050d5-d1fb-49f7-ac04-ecfe2e35bfcc
