### Create Partner
POST http://localhost:8080/partners
Content-Type: application/json

{
  "name": "foo"
}

### Get Partner - Add the ID from Create Partner from ServerLog
GET  http://localhost:8080/partners/d575cf42-97fd-4a36-8d64-4058b3aeca48


### Call Stubs
GET http://localhost:9876/api/persons
Content-Type: application/json
